"""empty message

Revision ID: 4594efe8142a
Revises: 4e5728a8b6a1
Create Date: 2021-09-16 11:14:12.833518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4594efe8142a'
down_revision = '4e5728a8b6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dislikes')
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###
